### PR TITLE
Schema updates

### PR DESCRIPTION
**Pull request by svbagwell**
Updated the collection schema files

File sources:
UMM-C
- [collection schema](https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/collection/v1.17.3/umm-c-json-schema.json)
- [cmn json schema](https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/collection/v1.17.3/umm-cmn-json-schema.json)

ECHO10
- [collection schema](https://git.earthdata.nasa.gov/projects/EMFD/repos/echo-schemas/browse/schemas/10.0/Collection.xsd)
- [MetadataCommon](https://git.earthdata.nasa.gov/projects/EMFD/repos/echo-schemas/browse/schemas/10.0/MetadataCommon.xsd)

DIF10
- [collection schema](https://git.earthdata.nasa.gov/projects/EMFD/repos/dif-schemas/browse/10.x/dif_v10.2.xsd)
- [UmmCommon](https://git.earthdata.nasa.gov/projects/EMFD/repos/dif-schemas/browse/10.x/UmmCommon_1.2.xsd)

### CODE REVIEW

**Comment by jenny-m-wood** [comment]
The ECHO10 collection schema linked in your comment above appears to take you to the ECHO10 granule schema. Can you double check this? @svbagwell

**Comment by svbagwell** [comment]
@jenny-m-wood my bad, i had too many tabs open. i updated the link

**Review by jenny-m-wood — APPROVED** [review]
From what I can tell, this LGTM

**Comment by slesaad** [comment]
looks good,. but maybe you should change the base branch to dev. accumulate all the updates there and make a release to main

**Comment by svbagwell** [comment]
base branch changed

**Pull request merged**
