### PR TITLE
Regression testing jat

### PR DESCRIPTION
**Pull request by John-Troutman**
Updates to umm-c, echo-c, and echo-g checks based on comments made in checks documents.

### CODE REVIEW

**Comment by spa0002** [comment]
Lgtm, since the checks are failing, perhaps we should resolve the ModuleNotFound errors for the files ( tests/test_checker.py
tests/test_custom_checker.py
tests/test_datetime_validator.py
tests/test_downloader.py
tests/test_schema_validator.py
tests/test_string_validator.py) in this PR?

**Review by spa0002 — COMMENTED** [review]
Lgtm, since the checks are failing, perhaps we should resolve the ModuleNotFound errors for the files ( tests/test_checker.py
tests/test_custom_checker.py
tests/test_datetime_validator.py
tests/test_downloader.py
tests/test_schema_validator.py
tests/test_string_validator.py) in this PR?

**Comment by spa0002** [comment]
For ex:
in main.py -
changing
`from code.utils import get_headers

if __name__ == '__main__':
    from code.checker import Checker
    from code.constants import COLOR, ECHO10_C, SUPPORTED_FORMATS
    from code.downloader import Downloader
    from code.utils import get_cmr_url, is_valid_cmr_url
else:
    from .code.checker import Checker
    from .code.constants import COLOR, ECHO10_C, SUPPORTED_FORMATS
    from .code.downloader import Downloader
    from .code.utils import get_cmr_url, is_valid_cmr_url
`
to
`if __name__ == '__main__':
    from code.checker import Checker
    from code.constants import COLOR, ECHO10_C, SUPPORTED_FORMATS
    from code.downloader import Downloader
    from code.utils import get_cmr_url, is_valid_cmr_url
    from code.utils import get_headers
else:
    from .code.checker import Checker
    from .code.constants import COLOR, ECHO10_C, SUPPORTED_FORMATS
    from .code.downloader import Downloader
    from .code.utils import get_cmr_url, is_valid_cmr_url
    from .code.utils import get_headers
`
and in test_checker.py changing
`from pyQuARC.code.checker import Checker

from .fixtures.checker import FUNCTION_MAPPING
from .common import read_test_metadata
`
to
`import sys
import os
sys.path.append(os.getcwd())
from tests.fixtures.checker import FUNCTION_MAPPING
from pyQuARC.code.checker import Checker
from tests.common import read_test_metadata
`

**Review by svbagwell — CHANGES_REQUESTED** [review]
Agree with Sam -- try changing the imports using his suggestion, then commit and push (no need to make a new PR, this one will update to reflect your commits). We'll see if that fixes the build error

**Comment by spa0002** [comment]
> Agree with Sam -- try changing the imports using his suggestion, then commit and push (no need to make a new PR, this one will update to reflect your commits). We'll see if that fixes the build error

@John-Troutman - you can check out the files ( tests/test_checker.py
tests/test_custom_checker.py
tests/test_datetime_validator.py
tests/test_downloader.py
tests/test_schema_validator.py
tests/test_string_validator.py) in my [PR](https://github.com/NASA-IMPACT/pyQuARC/pull/210/files#diff-35c2c975594deff3b752aa656843540afa1a28c37f8e5e4ffb3e8b719464c027) if you want to see how I edited them.

**Review by spa0002 — APPROVED** [review]

**Pull request merged**
