### PR TITLE
UMM-G support (SB)

### PR DESCRIPTION
**Pull request by svbagwell**
Added UMM-G support for the following checks:
- Range Date Time Logic Check 1
- Range Date Time Logic Check 2
- DateTime Format Check
- URL Health and Status Check
- Delete Time Check
- Characteristic Name Check

### CODE REVIEW

**Review by spa0002 — COMMENTED** [review]
In rule_mapping.json - 
For `characteristic_name_check`: need s's at the end of Platform and Instrument in the field names.

**Comment by svbagwell** [comment]
@spa0002 thanks for catching that! just pushed a commit with that fixed

**Comment by jenny-m-wood** [comment]
For the Characteristic Name Check, not sure it would apply for the sensor fields (e.g. "Platforms/Instruments/ComposedOf/Characteristics/Name"). Schema: https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/granule/v1.6.1/umm-g-json-schema.json#985

**Comment by jenny-m-wood** [comment]
In rule_mapping.json, need to add "OrbitCalculatedSpatialDomains/EquatorCrossingDateTime" for the datetime_format_check

**Review by jenny-m-wood — COMMENTED** [review]
In rule_mapping.json, need to add "OrbitCalculatedSpatialDomains/EquatorCrossingDateTime" for the datetime_format_check

**Review by spa0002 — APPROVED** [review]

**Review by jenny-m-wood — APPROVED** [review]

**Review by daniellegroenen — APPROVED** [review]
All looks good to me.

**Comment by esr0004** [comment]
In rule_mapping.json, need to add “MetadataSpecification/URL” for the url_check

**Review by esr0004 — COMMENTED** [review]
In rule_mapping.json, need to add “MetadataSpecification/URL” for the url_check

**Review by esr0004 — APPROVED** [review]

**Pull request merged**
